<?php

namespace Opifer\ManualBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * @return array
     */
    function getAllCategoriesWithArticles()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('a, c')
            ->leftJoin('c.articles', 'a');

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    function getAllCategories()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c');

        return $qb->getQuery()->getResult();
    }

}